AllCops:
  DisplayCopNames: true

Rails:
  Enabled: true

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Force before_filter until upgrade to Rails 4
Rails/ActionFilter:
  EnforcedStyle: filter

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Enabled: false

Style/Next:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/IndentHash:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/Proc:
  Enabled: false

Layout/SpaceInsideBrackets:
  Enabled: false

Style/WordArray:
  Enabled: false

Rails/Output:
  Enabled: false

Rails/HttpPositionalArguments:
  Enabled: false

# needs major refactorings before we can improve
Metrics/PerceivedComplexity:
  Max: 13
Metrics/MethodLength:
  Max: 49
Metrics/ClassLength:
  Max: 200
Metrics/AbcSize:
  Max: 72
Metrics/CyclomaticComplexity:
  Max: 36
Metrics/BlockLength:
  Max: 47
Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 6

Lint/UnusedMethodArgument:
  Enabled: false

# JobTemplates use this for inputs, we should probably whitelist classes
Security/YAMLLoad:
  Enabled: false
